[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.wezterm]
input_path = "~/.config/matugen/templates/wezterm.toml"
output_path = "~/.config/wezterm/colors/matugen.toml"

[templates.fish]
input_path = "~/.config/matugen/templates/fish.theme"
output_path = "~/.config/fish/themes/matugen.theme"
