[config.wallpaper]
command = "desktoppr"
arguments = ["scale", "fill"]
set = true

[templates.wezterm]
input_path = "~/.config/matugen/templates/wezterm.toml"
output_path = "~/.config/wezterm/colors/matugen.toml"

[templates.fish]
input_path = "~/.config/matugen/templates/fish.theme"
output_path = "~/.config/fish/themes/matugen.theme"

[templates.helix]
input_path = "~/.config/matugen/templates/helix.toml"
output_path = "~/.config/helix/themes/helix.toml"
