format = """
$directory \
$git_branch \
$git_status\
$fill\
[](fg:black)\
$time\
[](fg:black)\
\n$character
"""

[line_break]
disabled = true

[fill]
symbol = " "

[character]
success_symbol = "[󰘧](bold white)"
error_symbol = "[󰘧](bold red)"

[directory]
format = "(italic) [$path](bold bright-blue)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only = " "

[git_status]
untracked = "[ ](yellow)"
modified = "[ ](red)"
staged = "[ ](green)"
deleted = "[ ](red)"
ahead = "[ ](yellow)"
behind = "[ ](yellow)"
diverged = "[󰦻 ](cyan)"
conflicted = "[! ](red)"
stashed = ""
typechanged = ""
renamed = ""
up_to_date = ""
format = '$all_status$ahead_behind'

[git_branch]
symbol = "[](black)"
style = "fg:white bg:black"
format = '[$symbol $branch]($style)[](black)'

[time]
disabled = false
time_format = "%R"
style = "fg:bright-blue bg:black"
format = '[$time]($style)'
